In [9]:
import pandas as pd

df_vendas = pd.read_csv(r'C:\Users\Eiabe\Desktop\eletro\eletro_vendas.csv', encoding= 'latin-1', sep=';')
df_produtos = pd.read_csv(r'C:\Users\Eiabe\Desktop\eletro\eletro_produtos.csv')
df_clientes = pd.read_csv(r'C:\Users\Eiabe\Desktop\eletro\eletro_clientes.csv')

In [10]:
df_vendas.isna().sum()

id_venda         0
produto_id       0
cliente_id       0
quantidade      25
data_venda       0
observacao    1057
dtype: int64

In [11]:
df_vendas['quantidade'][pd.to_numeric(df_vendas['quantidade'], errors = 'coerce').isna()]

394    NaN
406    NaN
418    NaN
476    NaN
582    NaN
589    NaN
669    NaN
671    NaN
829    NaN
1226   NaN
1419   NaN
1462   NaN
1615   NaN
1629   NaN
1670   NaN
1700   NaN
1800   NaN
1932   NaN
1937   NaN
2154   NaN
2166   NaN
2285   NaN
2519   NaN
2578   NaN
2601   NaN
Name: quantidade, dtype: float64

In [12]:
duplicatas = df_vendas.columns.drop(['id_venda'])
df_vendas.duplicated(subset=duplicatas).sum()

np.int64(40)

In [13]:
df_vendas['observacao'].str.contains(',').sum()

np.int64(276)

In [14]:
df_vendas = df_vendas.drop_duplicates(subset=duplicatas, keep='first')
df_vendas = df_vendas.dropna(subset='quantidade')
df_vendas['quantidade'] = df_vendas['quantidade'].astype(int)

df_vendas['data_venda'] = pd.to_datetime(df_vendas['data_venda'])

df_vendas['observacao'] = df_vendas['observacao'].fillna("Sem Observação")

df_vendas = pd.merge(df_vendas, df_produtos, on = 'produto_id', how='left')
df_vendas = pd.merge(df_vendas, df_clientes, on='cliente_id', how='left')

display(df_vendas)

,id_venda,produto_id,cliente_id,quantidade,data_venda,observacao,nome_produto,categoria,preco,nome,cidade
0,V000001,13,9,1,2024-09-15 08:14:00,Entrega expressa solicitada,Hub USB,Acessórios,44.9,Isadora Brandão,Curitiba
1,V000002,6,3,4,2024-09-14 11:29:00,Compra feita via aplicação promocional,Cabo USB-C,Eletrônicos,24.9,Cecília Prado,São Paulo
2,V000003,4,16,2,2024-12-04 09:55:00,Cliente pediu embalagem para presente,Mouse Gamer,Eletrônicos,99.9,Pedro Henrique Lopes,Florianópolis
3,V000004,5,15,1,2024-10-22 17:56:00,Sem Observação,Teclado Mecânico,Eletrônicos,189.9,Olívia Marques,Joinville
4,V000005,9,5,3,2024-12-16 10:20:00,Sem Observação,Película de Vidro,Acessórios,14.9,Estela Cunha,Curitiba
...,...,...,...,...,...,...,...,...,...,...,...
2570,V002636,1,14,5,2024-10-25 19:16:00,Compra feita via aplicação promocional,Fone Bluetooth,Eletrônicos,89.9,Nathan Correia,São Paulo
2571,V002637,15,6,3,2024-11-08 17:41:00,Sem Observação,Microfone de Lapela,Eletrônicos,69.9,Fábio Lacerda,São Paulo
2572,V002638,2,7,3,2024-09-29 14:14:00,Sem Observação,Carregador Turbo,Eletrônicos,49.9,Giovana Peixoto,Joinville
2573,V002639,3,8,1,2024-10-05 11:23:00,Entrega expressa solicitada,Caixa de Som Portátil,Eletrônicos,129.9,Hugo Mendonça,Florianópolis
2574,V002640,4,13,2,2024-10-08 12:47:00,Compra feita via aplicação promocional,Mouse Gamer,Eletrônicos,99.9,Marcela Tavares,Curitiba

In [15]:
df_vendas.info()

<class 'pandas.DataFrame'>
RangeIndex: 2575 entries, 0 to 2574
Data columns (total 11 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   id_venda      2575 non-null   str
 1   produto_id    2575 non-null   int64
 2   cliente_id    2575 non-null   int64
 3   quantidade    2575 non-null   int64
 4   data_venda    2575 non-null   datetime64[us]
 5   observacao    2575 non-null   str
 6   nome_produto  2575 non-null   str
 7   categoria     2575 non-null   str
 8   preco         2575 non-null   float64
 9   nome          2575 non-null   str
 10  cidade        2575 non-null   str
dtypes: datetime64[us](1), float64(1), int64(3), str(6)
memory usage: 221.4 KB

In [16]:
df_vendas.describe()

,produto_id,cliente_id,quantidade,data_venda,preco
count,2575.000000,2575.000000,2575.000000,2575,2575.000000
mean,8.022524,10.437282,2.960388,2024-10-16 00:13:55.200000,82.315534
min,1.000000,1.000000,1.000000,2024-08-01 08:03:00,14.900000
25%,4.000000,6.000000,2.000000,2024-09-07 19:55:00,29.900000
50%,8.000000,10.000000,3.000000,2024-10-16 10:04:00,69.900000
75%,12.000000,15.000000,4.000000,2024-11-23 13:15:00,119.900000
max,15.000000,20.000000,5.000000,2024-12-29 22:12:00,249.900000
std,4.353043,5.753065,1.401237,NaN,62.987108

In [17]:
df_vendas['preco'][pd.to_numeric(df_vendas['preco'], errors='coerce').isna()]

Series([], Name: preco, dtype: float64)

In [19]:
df_vendas.to_csv(r'C:\Users\Eiabe\Desktop\eletro\eletro_vendas.csv', index=False)